# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import jchannel_pb2 as jchannel__pb2


class JChannelsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.stream_stream(
                '/cn.yingming.grpc1.JChannelsService/connect',
                request_serializer=jchannel__pb2.Request.SerializeToString,
                response_deserializer=jchannel__pb2.Response.FromString,
                )
        self.ask = channel.unary_unary(
                '/cn.yingming.grpc1.JChannelsService/ask',
                request_serializer=jchannel__pb2.ReqAsk.SerializeToString,
                response_deserializer=jchannel__pb2.RepAsk.FromString,
                )


class JChannelsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JChannelsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.stream_stream_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=jchannel__pb2.Request.FromString,
                    response_serializer=jchannel__pb2.Response.SerializeToString,
            ),
            'ask': grpc.unary_unary_rpc_method_handler(
                    servicer.ask,
                    request_deserializer=jchannel__pb2.ReqAsk.FromString,
                    response_serializer=jchannel__pb2.RepAsk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cn.yingming.grpc1.JChannelsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JChannelsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/cn.yingming.grpc1.JChannelsService/connect',
            jchannel__pb2.Request.SerializeToString,
            jchannel__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cn.yingming.grpc1.JChannelsService/ask',
            jchannel__pb2.ReqAsk.SerializeToString,
            jchannel__pb2.RepAsk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
