# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import testbuf_pb2 as testbuf__pb2


class TestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start = channel.stream_stream(
                '/Test/start',
                request_serializer=testbuf__pb2.Request.SerializeToString,
                response_deserializer=testbuf__pb2.Response.FromString,
                )
        self.ask = channel.unary_unary(
                '/Test/ask',
                request_serializer=testbuf__pb2.ReqAsk.SerializeToString,
                response_deserializer=testbuf__pb2.RepAsk.FromString,
                )


class TestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start': grpc.stream_stream_rpc_method_handler(
                    servicer.start,
                    request_deserializer=testbuf__pb2.Request.FromString,
                    response_serializer=testbuf__pb2.Response.SerializeToString,
            ),
            'ask': grpc.unary_unary_rpc_method_handler(
                    servicer.ask,
                    request_deserializer=testbuf__pb2.ReqAsk.FromString,
                    response_serializer=testbuf__pb2.RepAsk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Test', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Test(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Test/start',
            testbuf__pb2.Request.SerializeToString,
            testbuf__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Test/ask',
            testbuf__pb2.ReqAsk.SerializeToString,
            testbuf__pb2.RepAsk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
